server:
  port: 3002
spring:
  application:
    name: static-service
  mvc:
    # 配置静态资源可以被访问！
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false


